# Reference : https://github.com/mojombo/jekyll/wiki/Configuration

BASE_PATH : /inject

# site info
name      : Inject
version   : 0.4.0
stable_dl : releases/v0.4.x/inject-v0.4.0.zip
description :
    short : Dependency Management got Awesome
    long  : CommonJS and AMD Compliant dependency loader for modern web apps

# documentation structure
documentation: 
  - version: 0.4.x
    categories: 
      - cat: api
        name: API
      - cat: howto
        name: How To

# permalinks
permalink : /:categories/:year/:month/:day/:title.html

# copyright notice
copyright :
  holder  : LinkedIn Corporation
  year    : 2012

# authors
authors :
  jheuser :
    name : Jakob Heuser
    li_pub_profile : jakobheuser
    li_pic_url : https://m1-s.licdn.com/mpr/mpr/shrink_60_60/p/1/000/03f/2b3/1456141.jpg
    github : Jakobo
    twitter : jakobo
  jhoff :
    name : Jordan Hoff
    li_pub_profile : jordanhoff
    li_pic_url : https://m1-s.licdn.com/mpr/mpr/shrink_60_60/p/1/000/094/13f/3e7fa8b.jpg
    github : jhoff
    twitter : jhoff484

# publish posts with a future date
future    : true

# The production_url is only used when full-domain names are needed such as sitemap.txt 
production_url : http://www.injectjs.com

# build config
auto      : true

# github defaults
lsi       : false
pygments  : true
safe      : true

# overrides maruku
markdown  : kramdown
kramdown  :
  entity_output : symbolic

# asset management
assets :
  cacheBurst : true
  stylesheets :
    - main
  vendor :
    scripts :
      jQuery :
        version : 1.8.2
        
lang      : en

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
analytics :
  provider : google 
  google : 
    tracking_id : 'UA-1545927-5'