# Reference : https://github.com/mojombo/jekyll/wiki/Configuration

# site info
name      : Inject
version   : 0.4.2
stable_dl : /download/v0.4.x/inject-v0.4.2.zip
description :
    short : Dependency Management got Awesome
    long  : CommonJS and AMD Compliant dependency loader for modern web apps

# documentation structure
documentation:
  - version: 0.4.x
    categories:
      - cat: api
        name: API
      - cat: howto
        name: How To

# permalinks
permalink : /:categories/:year/:month/:day/:title.html

# copyright notice
copyright :
  holder  : LinkedIn Corporation
  year    : 2012

# authors
authors :
  jheuser :
    name : Jakob Heuser
    li_pub_profile : jakobheuser
    li_pic_url : https://m1-s.licdn.com/mpr/mpr/shrink_60_60/p/1/000/03f/2b3/1456141.jpg
    github : Jakobo
    twitter : jakobo
  jhoff :
    name : Jordan Hoff
    li_pub_profile : jordanhoff
    li_pic_url : https://m1-s.licdn.com/mpr/mpr/shrink_60_60/p/1/000/094/13f/3e7fa8b.jpg
    github : jhoff
    twitter : jhoff484
  mpowell :
    name : Matt Powell
    li_pub_profile: mttpwll
    li_pic_url: https://m1-s.licdn.com/mpr/mpr/shrink_60_60/p/3/000/095/332/3c93849.jpg
    github: mattpowell
    twitter: mattpowell

# publish posts with a future date
future    : true

# The production_url is only used when full-domain names are needed such as sitemap.txt
production_url : http://www.injectjs.com

# build config
auto      : true

# github defaults
lsi       : false
pygments  : true
safe      : true

# overrides maruku
markdown  : kramdown
kramdown  :
  entity_output : symbolic

# asset management
assets :
  cacheBurst : true
  stylesheets :
    - main
  vendor :
    scripts :
      jQuery :
        version : 1.8.2

# language
lang      : en

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
analytics :
  provider : google
  google :
    tracking_id : 'UA-1545927-5'

# Settings for Disqus
# Set 'shortname' to the disqus shortname
# Set 'developer' to 0 in production, 1 in development to view proper comments
disqus :
  shortname : injectjs
  developer : 0
